# Generated by Django 4.2 on 2023-05-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('background', models.FileField(upload_to='background/')),
                ('phone', models.CharField(max_length=20)),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('whats_app', models.URLField()),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
