# Generated by Django 4.2 on 2023-05-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=55)),
                ('instagram', models.URLField()),
                ('address', models.CharField(max_length=255)),
                ('graphic', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=5555)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_images/')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=550)),
                ('age', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
